---
title: "Books"
---


*[Visualizing Linear Models](https://www.dpbolvw.net/click-100373821-12898971?url=https%3A%2F%2Fwww.springer.com%2Fgp%2Fbook%2F9783030641665%3FcountryChanged%3Dtrue)* (Springer, 2021) - This short textbook introduces the theory of linear models, emphasizing two important and complementary ways of visualizing the concepts: the *observations* picture and the *variables* picture. Accompanying flash cards ([anki](static/books/visualizing-linear-models.apkg) | [printable](static/books/visualizing-linear-models-printable-cards.pdf) | [document](static/books/visualizing-linear-models-exercises.pdf)) help reinforce the material.


*Visualizing Random Variables* - This will be a follow-up to *Visualizing Linear Models* that encourages the student to extend the two-pictures idea to random vectors more generally by understanding $L^2$ spaces using intuition from Euclidean space.


*[Data Analysis with R: The Big Picture](static/books/Data-Analysis-with-R.pdf)* - A gentle and systematic introduction for complete beginners. This book is almost finished, and I've used it for courses. It may eventually be expanded into a more computational and up-to-date textbook called *Data Science Workflow with R and the tidyverse*.


*A Systematic Guide to Mathematical Statistics* - This is a long-term project, but early drafts of some sections are posted below.

- [1-1 Topological spaces](static/books/1-1-topological-spaces.pdf)
- [1-4 Normed spaces](static/books/1-4-normed-spaces.pdf)
- [1-5 Inner product spaces](static/books/1-5-inner-product-spaces.pdf)
- [2-1 Measurable spaces](static/books/2-1-measurable-spaces.pdf)
- [2-2 Measures](static/books/2-2-measures.pdf)
- [2-3 Integrals](static/books/2-3-integrals.pdf)
- [2-4 Probability measures and expectations](static/books/2-4-probability-measures-and-expectations.pdf)
- [2-5 Product spaces](static/books/2-5-product-spaces.pdf)
- [2-6 Spaces of measurable functions](static/books/2-6-spaces-of-measurable-functions.pdf)
- [2-7 Metric spaces of measures](static/books/2-7-metric-spaces-of-measures.pdf)
- [3-3 Information theory](static/books/3-3-information-theory.pdf)