---
title: "Selected workshop materials"
---


## Mixed Effects Modeling with R

A *random effect* is a model coefficient that is itself modeled as a random draw from a distribution that may, in turn, involve unknown parameters. A *linear mixed effects model* can have both terms with fixed (unknown) coefficients and terms with random coefficients. This workshop begins by clarifying linear mixed effects models as a generalization of ordinary linear models then quickly moves into four concrete examples, while drawing plenty of plots to aid your understanding. ([video](https://www.youtube.com/watch?v=JfWHZBfhOvE) | [slides](static/teaching/Mixed-Effects-Modeling-with-R.pdf) | [script](static/teaching/iterative-fitting-solutions.r))



## Principal Component Analysis with R

*Principal components analysis (PCA)* is a technique for reducing the dimension of your data while preserving their "shape" as well as possible. In the first part of the workshop, we'll cover the theory behind PCA. After that, we'll work through several examples together using R. ([slides](static/teaching/Principal-Components-Analysis-with-R.pdf) | [script](static/teaching/PCA.r))


## Python series

#### Session 1: Intro
- Anaconda Navigator and Spyder
- language basics
- importing
- file manipulation
- string manipulation, including regular expressions

#### Session 2: Showcase
- system commands
- web scraping (requests, BeautifulSoup)
- scheduled tasks
- databases (SQLite, SQLAlchemy)
- apps (Flask)

#### Session 3: Data Science and Machine Learning
- SciPy ecosystem (NumPy, Pandas, SciPy, Matplotlib)
- Jupyter notebooks
- scikit-learn

#### Session 4: Project
- Federalist Papers (web scraping, NLP feature extraction, dimension reduction, classification)

All Python workshop files are hosted on GitHub ([Sessions 1 & 2](https://github.com/quantitations/python-day1) | [Sessions 3 & 4](https://github.com/quantitations/python-day2))

